[settings]
python.uv_venv_auto = true

[tools]
python = "3.13"
ruff = "latest"

[tasks.test]
description = "Run tests"
run = "python -m pytest"

[tasks.lint]
description = "Lint the code"
run = "ruff check ."

[tasks.nushell-verifier]
description = "Run nushell-verifier"
alias = "nv"
run = "uv run nushell-verifier"

