[settings]
python.uv_venv_auto = true

[tools]
python = "3.13"
ruff = "latest"

[tasks.install]
description = "Install dependencies"
alias = "i"
run = "uv pip install -r requirements.txt"

[tasks.test]
description = "Run tests"
run = "python -m pytest"

[tasks.lint]
description = "Lint the code"
run = "ruff check ."

[tasks.nushell-verifier]
description = "Run nushell-verifier"
alias = "nv"
run = "python -m nushell_verifier"

